/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function decrypt(ciphertext: string, key: string): string

export declare function encrypt(plaintext: string, key: string): string

export declare function generateOneTimeKeys(qty: number, accountName: string, prefix: string): Array<OneTimeKey>

export declare function helloCrypto(): string

export interface OneTimeKey {
  accountName: string
  secretName: string
  id: string
  pubKey: string
  privateKey: string
}

export declare function randomBytes(length: number): Array<number>
