/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class DsaKeyPair {
  privateKey: string
  publicKey: string
}
export type DSAKeyPair = DsaKeyPair

export declare function decapsulate(length: KemLength, privateKeyBase64: string, ciphertextBase64: string): string

export declare function decrypt(ciphertext: string, key: string): string

export declare function encapsulate(length: KemLength, publicKeyBase64: string): EncapsulationResult

export interface EncapsulationResult {
  ciphertext: string
  sharedSecret: string
}

export declare function encrypt(plaintext: string, key: string): string

export declare function generateOneTimeKeys(length: KemLength, qty: number, accountName: string, prefix: string): Array<OneTimeKey>

export declare function helloCrypto(): string

export declare function kemKeypair(length: KemLength): KemKeyPair

export interface KemKeyPair {
  privateKey: string
  publicKey: string
}

export declare const enum KemLength {
  MlKem1024 = 0,
  MlKem768 = 1,
  MlKem512 = 2,
}

export declare function mlDsaKeypair(length: MlDsaLength): DsaKeyPair

export declare const enum MlDsaLength {
  MlDsa87 = 0,
  MlDsa65 = 1,
  MlDsa44 = 2,
}

export interface OneTimeKey {
  accountName: string
  secretName: string
  id: string
  pubKey: string
  privateKey: string
}

export declare function randomBytes(length: number): Uint8Array
