/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function decapsulate(length: KemLength, privateKey: Uint8Array, ciphertext: Uint8Array): Uint8Array

export declare function decrypt(ciphertext: Uint8Array, key: Uint8Array): Uint8Array

export interface DsaKeyPair {
  privateKey: Uint8Array
  publicKey: Uint8Array
}

export declare function encapsulate(length: KemLength, publicKey: Uint8Array): EncapsulationResult

export interface EncapsulationResult {
  ciphertext: Uint8Array
  sharedSecret: Uint8Array
}

export declare function encrypt(plaintext: Uint8Array, key: Uint8Array): Uint8Array

export declare function generateOneTimeKeys(length: KemLength, qty: number, accountName: string, prefix: string): Array<OneTimeKey>

export declare function helloCrypto(): string

export declare function kemKeypair(length: KemLength): KemKeyPair

export interface KemKeyPair {
  privateKey: Uint8Array
  publicKey: Uint8Array
}

export declare const enum KemLength {
  MlKem1024 = 0,
  MlKem768 = 1,
  MlKem512 = 2,
}

export declare function mlDsaKeypair(length: MlDsaLength): DsaKeyPair

export declare const enum MlDsaLength {
  MlDsa87 = 0,
  MlDsa65 = 1,
  MlDsa44 = 2,
}

export declare function mlDsaSign(length: MlDsaLength, privateKey: Uint8Array, message: Uint8Array): Uint8Array

export declare function mlDsaVerify(length: MlDsaLength, publicKey: Uint8Array, message: Uint8Array, signature: Uint8Array): boolean

export interface OneTimeKey {
  accountName: string
  secretName: string
  id: string
  pubKey: Uint8Array
  privateKey: Uint8Array
}

export declare function randomBytes(length: number): Uint8Array
